name: OWASP ZAP Full Security Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'https://halaqi.vercel.app'
          fail_action: false
          allow_issue_writing: false
